name: AIO #name of the plugin (in this case, AIO)
version: 1.0.0 #version of the plugin
author: flaxeneel2 #author (in this case, me)
softdepend:
  - PlaceholderAPI #softdepend on PlaceHolderAPI for a future commit
main: io.github.flaxeneel2.AIO.Main #main file of the plugin

#Commands bellow
commands:
  aio:
    description: "base command"
    aliases:
      - allinone
      - aliastest
  balance:
    description: "shows balance"
    aliases:
      - bal
  setbalance:
    description: "Sets a player's balance"
    aliases:
      - setbal